steps: 
    - name: 'gcr.io/cloud-builders/docker'
      args: ["build","--no-cache=true",
           "-t", "gcr.io/yassir-maps/yamaps_front_demo_$BRANCH_NAME:v$SHORT_SHA","-t",
           "gcr.io/yassir-maps/yamaps_front_demo_$BRANCH_NAME:latest", 
           "."]

    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/yassir-maps/yamaps_front_demo_$BRANCH_NAME:v$SHORT_SHA"]
    
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/yassir-maps/yamaps_front_demo_$BRANCH_NAME:latest"]

    - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
      - '-c'
      - |
        gcloud components install kubectl
        gcloud container clusters get-credentials yamaps-$BRANCH_NAME-cluster --zone europe-west1-d --project yassir-maps
        kubectl set image deployment/yamaps_front_demo yamaps_front_demo=gcr.io/yassir-maps/gcr.io/yassir-maps/yamaps_front_demo_$BRANCH_NAME:v$SHORT_SHA

timeout: 1200s
       